"""Plots of stellar structure
"""

"""
ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.plot(m/m.max(), r/r.max(), label="radius $y = R$")
pyplot.plot(m/m.max(), rho/rho.max(), label="density $y = \\rho$")
pyplot.plot(m/m.max(), P/P.max(), label="pressure $y = P$")
pyplot.plot(m/m.max(), T/T.max(), label="tempurature $y = T$")
pyplot.plot(m/m.max(), L/L.max(), label="luminosity $y = L$")
pyplot.plot(m/m.max(), k_R/k_R.max(), label="mean opacity $y = k_R$")
pyplot.plot(m/m.max(), power_density/power_density.max(), label="power density $y = \\varepsilon \\rho$")
pyplot.xlabel("mass coordinate")
pyplot.ylabel("parameter $y$ fraction of maximum")
pyplot.legend()
pyplot.show(ifig)

ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.plot(r, m/m.max(), label="mass $y = M$")
pyplot.plot(r, rho/rho.max(), label="density $y = \\rho$")
pyplot.plot(r, P/P.max(), label="pressure $y = P$")
pyplot.plot(r, T/T.max(), label="tempurature $y = T$")
pyplot.plot(r, L/L.max(), label="luminosity $y = L$")
pyplot.plot(r, k_R/k_R.max(), label="mean opacity $y = k_R$")
pyplot.plot(r, power_density/power_density.max(), label="power density $y = \\varepsilon \\rho$")
pyplot.xlabel("radius [cm]")
pyplot.ylabel("parameter $y$ fraction of maximum")
pyplot.legend()
pyplot.show(ifig)

ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.plot(r, rho)
pyplot.xlabel("radius [cm]")
pyplot.ylabel("rho [g/cm^3]")
pyplot.title("density")
pyplot.show(ifig)

ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.plot(r, T)
pyplot.xlabel("radius [cm]")
pyplot.ylabel("temperature [K]")
pyplot.title("Temperature")
pyplot.show(ifig)

ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.semilogy(r, mfp)
pyplot.xlabel("radius [cm]")
pyplot.ylabel("mean free path [cm]")
pyplot.title("Opacity: Mean free path of light")
pyplot.show(ifig)

ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.plot(r, power_density)
pyplot.xlabel("radius [cm]")
pyplot.ylabel("power density [erg/(s cm^3)]")
pyplot.title("Nuclear power density")
pyplot.show(ifig)

ifig += 1; pyplot.close(ifig); pyplot.figure(ifig)
pyplot.plot(r, m)
pyplot.xlabel("radius [cm]")
pyplot.ylabel("mass [g]")
pyplot.title("total mass")
pyplot.show(ifig)
"""
